#!/usr/bin/env bash

function getRepoStats () {
  cd "$1"
  if [ -d ".git" ]; then
    IFS=' ' read -a STATS <<< $(git log --pretty=tformat: --numstat | awk '{inserted+=$1; deleted+=$2; delta+=$1-$2} END {print inserted, deleted, delta}')
    echo "## $1" >> ../gitstats.md
    echo "* Inserted      : ${STATS[0]}" >> ../gitstats.md
    echo "* Deleted       : ${STATS[1]}" >> ../gitstats.md
    echo "* Lines of code : ${STATS[2]}" >> ../gitstats.md
    echo "" >> ../gitstats.md
  else
    IFS=' ' read -a STATS <<< "0 0 0"
  fi
  cd ..
}

echo "# Git Statistics" >> gitstats.md
echo "" >> gitstats.md

TOTALSTATS=(0 0 0)
for directories in */ ; do
  getRepoStats $directories

  TOTALSTATS[0]=`expr ${TOTALSTATS[0]} + ${STATS[0]}`
  TOTALSTATS[1]=`expr ${TOTALSTATS[1]} + ${STATS[1]}`
  TOTALSTATS[2]=`expr ${TOTALSTATS[2]} + ${STATS[2]}`
done

echo  "---" >> gitstats.md
echo  "## Total Inserted      : ${TOTALSTATS[0]}" >> gitstats.md
echo  "## Total Deleted       : ${TOTALSTATS[1]}" >> gitstats.md
echo  "## Total Lines of code : ${TOTALSTATS[2]}" >> gitstats.md
