export DEFAULT_USER=`whoami`
export USER=`whoami`

# Path to oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="spaceship"

# Changes format of command execution time stamp shown in the history command output.
HIST_STAMPS="dd/mm/yyyy"

plugins=(
  brew
  colorize
  colored-man-pages
  docker
  git
  git-extras
  github
  gnu-utils
  golang
  osx
  taskwarrior
  tmux
  virtualenv
  zsh-autosuggestions
  zsh-syntax-highlighting
)

# Paths
export DEV=$HOME/Development
export GOPATH=$DEV/go
export PATH=$PATH:$GOPATH/bin:$HOME/.scripts:/snap/bin

source $ZSH/oh-my-zsh.sh
