export DEFAULT_USER=`whoami`
export USER=`whoami`

# Path to oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="juanghurtado"

# Changes format of command execution time stamp shown in the history command output.
HIST_STAMPS="dd/mm/yyyy"

plugins=(git git-extras osx colored-man-pages docker github stack tmux taskwarrior)

# Alias
alias -g nixi='nix-env -iA'
alias -g nixiu='nix-env -f https://github.com/NixOS/nixpkgs-channels/archive/nixos-unstable.tar.gz -i'
alias -g nixqu='nix-env -f https://github.com/NixOS/nixpkgs-channels/archive/nixos-unstable.tar.gz -qa'

# Paths
export DEV=$HOME/Development
export GOPATH=$DEV/go
export PATH=$PATH:$GOPATH/bin:$HOME/.scripts

source $ZSH/oh-my-zsh.sh
